index: 20201026 Blockchain Learning Challenge
decredcommunity/events pull request #78
Opened 2020-12-11 20:23 UTC by xaur

2021-01-12 05:00 UTC, adcadde requested changes
Small changes on the youtube links and a few notes.

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +title_es: { any? remove if not needed }
Same as EN, remove.

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +    presenters: { who? }
elian, adcade

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +      - { link? }
Was right after 'How to become a Decred contractor?' and we stopped the recording, so no media link for this one.

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +  - url: https://www.youtube.com/watch?v=kBjgLcDZW8k
https://youtu.be/kBjgLcDZW8k

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=epZY2put3zQ
https://youtu.be/epZY2put3zQ

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=rTjVKqKLI1w
https://youtu.be/rTjVKqKLI1w

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=8GwzMhoEyO4
https://youtu.be/8GwzMhoEyO4

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=uuYf8Z28TcA
https://youtu.be/uuYf8Z28TcA

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=kqbejo0sA5c
https://youtu.be/kqbejo0sA5c

2021-01-12 05:00 UTC, adcadde commented on index/20201026.1.yml
> +  - url: https://www.youtube.com/watch?v=czqQTw4VNBM
https://youtu.be/czqQTw4VNBM

2021-01-13 03:13 UTC, xaur commented on index/20201026.1.yml
> +  - url: https://www.youtube.com/watch?v=kBjgLcDZW8k
Note that I am deliberately using full "canonical" YouTube links everywhere as a rule. This is esp. relevant for links that people end up posting on Reddit: submissions with exact same link are linked together and are shown on the Duplicates or "Other Discussions" tab. When links differ, even slightly, they are not linked.

2021-01-13 03:13 UTC, xaur commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=epZY2put3zQ
Same as above.

2021-01-13 03:13 UTC, xaur commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=rTjVKqKLI1w
Same as above.

2021-01-13 03:14 UTC, xaur commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=8GwzMhoEyO4
Same as above.

2021-01-13 03:14 UTC, xaur commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=uuYf8Z28TcA
Same as above.

2021-01-13 03:14 UTC, xaur commented on index/20201026.1.yml
> +      - https://www.youtube.com/watch?v=kqbejo0sA5c
Same as above.

2021-01-13 03:14 UTC, xaur commented on index/20201026.1.yml
> +  - url: https://www.youtube.com/watch?v=czqQTw4VNBM
Same as above.

2021-01-13 03:16 UTC, xaur commented
Thanks for the review (and the challenge, ofc) @adcadde! This item is a big one but we're almost done. One last question remaining: was "final projects and winners" [video](https://www.youtube.com/watch?v=CQTitBVUMMY) livestreamed or was something people "connected to", or was it just posted on your YT channel? I am thinking whether it should be placed in "subevents" or "media".

2021-01-13 04:31 UTC, adcadde commented
The video was posted on YouTube, therefore, better placed at "media". Thanks, bee!

2021-01-13 19:55 UTC, xaur commented
Ok all good now, merged.

This was an epic index entry that really stress-tested my system and helped to shape the [spec](https://github.com/decredcommunity/events/blob/master/docs/index-spec.md) by formalizing the concept of "subevents".

Final link:

- https://decredcommunity.github.io/events/index/20201026.1

Don't hesitate to jump in #85 and share your experience/ideas to improve the index!

2021-01-13 19:55 UTC, closed without merging